version: '3'
services:

  postgres:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata 

  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka_server:
    image: bitnami/kafka
    container_name: kafka_server
    ports:
      - 9091:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes 
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  kafka_client:
    image: bitnami/kafka
    container_name: kafka_client
    ports:
      - 9093:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - kafka_server
    command: kafka-topics.sh 
      --create 
      --zookeeper zookeeper:2181 
      --replication-factor 1 
      --partitions 1 
      --topic alert
  
  app:
    image: evankrasnikov/app
    container_name: app
    depends_on:
      - postgres
      - zookeeper
      - kafka_server
      - kafka_client
    command: tail -F /dev/null